### ISSUE TITLE
Split words when case changes

### ISSUE THREAD

**Issue by raklaptudirm** [codespell-project/codespell#2347] opened 2022-05-10 09:29 UTC
Currently, codespell thinks that a variable name like `actualY` is a misspelling of `actually`. Splitting words when the case changes from lower to upper should be added.

**Comment by peternewman** [comment] 2022-05-10 12:43
Hi @raklaptudirm ,

This is known as camelCase, so it's a duplicate of #196 .

**Closed by peternewman** 2022-05-10 12:43 UTC
