### ISSUE TITLE
vscode extension?

### ISSUE THREAD

**Issue by ssbarnea** [codespell-project/codespell#1875] opened 2021-02-06 09:16 UTC
It would really be great to be able to run codespell in vscode and be able to identify errors inside "problems" tab.

As I know that writing an extension is not very easy, I think we should keep this open until someone either writes one or find a way to re-use existing one to enable this feature.

**Comment by peternewman** [comment] 2021-02-08 15:34
Hi @ssbarnea ,

I know nothing about vscode, but it's my understanding that our problem matcher:
https://github.com/codespell-project/codespell-problem-matcher/blob/master/codespell-matcher.json

Is based on the same/similar syntax to the vscode one.

I'm assuming you can just run a program across the code and feed the output into a matcher to generate the problems tab content?

**Comment by peternewman** [comment] 2022-10-18 11:18
Duplicate of #1203

**Closed by peternewman** 2022-10-18 11:18 UTC
Labels: enhancement, duplicate
