### ISSUE TITLE
setup.cfg and .codespellrc not autodetected

### ISSUE THREAD

**Issue by daniel-wtd** [codespell-project/codespell#1707] opened 2020-10-22 16:24 UTC
Hi,

I have setup a .codespellrc according to the README, but it seems to be ignored per default. It also does not matter, if the file is renamed to setup.cfg.

```
# .codespellrc
[codespell]
skip = ./.git/*
quiet-level = 3
```

```
(.venv-python3) dschier ~/Projects/while-true-do/repo-template (master *%) $ codespell --version
1.17.1
(.venv-python3) dschier ~/Projects/while-true-do/repo-template (master *%) $ codespell
WARNING: Binary file: ./.git/index 
WARNING: Binary file: ./.git/objects/e5/ad7781c5756fc73eca6c5a42bbd0968f9e92af
....
```

**Comment by larsoner** [comment] 2020-10-22 16:27
Are you on latest `master` or the latest release? The README on github is valid for latest master, to see what the latest release has you can look at https://pypi.org/project/codespell/

**Comment by larsoner** [comment] 2020-10-22 16:28
Closing as implicit dupe of #1698

**Closed by larsoner** 2020-10-22 16:28 UTC
