### ISSUE TITLE
Ignore new line character when checking for a word

### ISSUE THREAD

**Issue by jooola** [codespell-project/codespell#2508] opened 2022-09-29 11:20 UTC
I have a print statement that starts with a new line char and some text. Code spell is failing as it includes the `n` from `\n` in the next word:

```
print("\nWe have ...\n")
```

Will suggest `nWe ==> new`

**Comment by peternewman** [comment] 2022-10-17 11:21
Agreed, but it's a duplicate of #1774

**Closed by peternewman** 2022-10-17 11:21 UTC
