### ISSUE TITLE
Consider escaped character sequences

### ISSUE THREAD

**Issue by mdeweerd** [codespell-project/codespell#2394] opened 2022-07-05 19:47 UTC
In a php file:
```php
<?php
$a="\nin ";
```

Codespell reports:
```raw
nin ==> inn, min, bin, nine
```

Maybe codespell could consider escaped sequences.

**Comment by luzpaz** [comment] 2022-07-05 22:30
Dupe of #1774

**Closed by luzpaz** 2022-07-05 22:30 UTC
