### ISSUE TITLE
Allow comments on entries in ignored-words-file 

### ISSUE THREAD

**Issue by pdbj** [codespell-project/codespell#2781] opened 2023-03-09 17:40 UTC
It would be nice to allow comments on the entries in the `ignore_words_file`:

```
peripherial # from the hash collision table
```

Looks like [this line](https://github.com/codespell-project/codespell/blob/29a4e2af62fb61a3fac163d5b976bd66fe00dc57/codespell_lib/_codespell.py#L624) is the place:

```
for line in f:
    line = line.partition(' #')[0]
    line = line.rstrip()
    ignore_words.add(line)
```

**Comment by DimitriPapadopoulos** [comment] 2023-03-09 18:31
Duplicate of #2063.

**Closed by DimitriPapadopoulos** 2023-03-09 18:31 UTC
Labels: duplicate
