### ISSUE TITLE
Enable defining settings using comma-separated-values as lists

### ISSUE THREAD

**Issue by paduszyk** [codespell-project/codespell#3206] opened 2023-11-10 20:49 UTC
This is a proposal for a minor update in defining some settings.

Settings involving sequences of values (e.g. words to be ignored, files to be skipped) could be declared not as comma-separated strings, but as lists.

The idea particularly regards `pyproject.toml`, but could be potentially applicable to pre-commit hook as well.

Of course, I think we can all live with the way it's implemented now, but I guess using lists would make the `codespell` configuration more consistent with the remaining tools set up in the config files.

Anyway, the tool is great! I thank all the contributors for their efforts! 🙇🏻‍♂️ 👍🏻

**Comment by DimitriPapadopoulos** [comment] 2023-11-10 23:34
Isn't this a duplicate of #2767?

**Comment by dalito** [comment] 2024-01-14 23:27
I went from here to #2727 and learnt there that #2727 is for adding support for strings with comma separated items (all in one string). That PR is not trying to add the standard notation of the configuration formats for lists.

@paduszyk - Do you mean the below way of specification in this issue?

In toml
```toml
[tool.codespell]
skip = [
  'bad.txt',
  'whatever.txt',
]
count = false
```

In setup.cfg
```ini
[codespell]
skip =
    bad.txt
    whatever.txt
count =
```

**Comment by DimitriPapadopoulos** [comment] 2024-01-16 15:13
@dalito As far as the INI format of `setup.cfg` is concerned, I think there is a misunderstanding. Lists are always comma-separated in INI files. Your example is about multiline values which are already [supported by configparser](https://docs.python.org/3/library/configparser.html#supported-ini-file-structure):
> ```ini
> [Multiline Values]
> chorus: I'm a lumberjack, and I'm okay
>     I sleep all night and I work all day
> ```
As for having real lists in TOML files instead of comma-separated values, that does seem to be the issue at hand here, which I tried to address in https://github.com/codespell-project/codespell/pull/2767/commits/f5355b9660be5b38d83fc20b88c774f355244565 - but tests don't pass so far.

**Closed** 2024-01-19 18:13 UTC

**Comment by dalito** [comment] 2024-01-19 20:15
> @dalito As far as the INI format of `setup.cfg` is concerned, I think there is a misunderstanding. Lists are always comma-separated in INI files. Your example is about multiline values which are already [supported by configparser](https://docs.python.org/3/library/configparser.html#supported-ini-file-structure):
> 

@DimitriPapadopoulos - Just FYI: An example in the linked docs is:
```
extensions =
  enabled_extension
  another_extension
  #disabled_by_comment
  yet_another_extension
```
This is not comma-separated but new-line separated. But I am completely happy with toml being supported now.

**Comment by DimitriPapadopoulos** [comment] 2024-01-20 13:05
I'll try to turn multiline values in config files into comma-separated values in a different commit, since the documentation of [configparser](https://docs.python.org/3/library/configparser.html#customizing-parser-behaviour) seems to imply such multiline values should be interpreted as lists::
```ini
extensions =
  enabled_extension
  another_extension
  #disabled_by_comment
  yet_another_extension
```
