### ISSUE TITLE
[2.2.6] `--ignore-words-list Nd` has no effect, "Nd" is still reported as a typo

### ISSUE THREAD

**Issue by hartwork** [codespell-project/codespell#3233] opened 2023-11-26 16:57 UTC
Hi!

Thanks for making and sharing codespell as Software Libre! :pray: I'm happily using codespell in CI with libexpat (https://github.com/libexpat/libexpat/pull/739).

I ran into an issue with recent codespell where two-letter word "Nd" in `--ignore-words-list` is ignored apparently. To reproduce:

```console
# codespell --version
2.2.6

# cd "$(mktemp -d)"
# git clone --depth 1 https://github.com/tenox7/ttyplot
# cd ttyplot/
# codespell  --skip ./.git --ignore-words-list Nd
./ttyplot.1:6: Nd ==> And, 2nd

# sed -n 6p ttyplot.1
.Nd realtime terminal plotting utility
```

This seems like a bug in codespell?

For a workaround, is there some way I can make this work without sacrificing all typo detection for the man page?

Thanks and best, Sebastian

**Comment by DimitriPapadopoulos** [comment] 2023-11-27 07:26
See #3210 which is itself a duplicate of a multitude of other issues.

**Closed** 2023-11-27 07:28 UTC
Labels: duplicate

**Comment by hartwork** [comment] 2023-11-27 15:12
@DimitriPapadopoulos thanks for your reply! It took me a bit to understand #3210 and how it would be related to my case given title "Case-sensitivity of ignored words" but now it's clear that to ignore `Nd` (with uppercase "N") I need to pass `--ignore-words-list nd` (with lowercase "n"). Good to know!
